// Message variant pools to eliminate repetition in automated messages
// Each pool contains 20+ variants maintaining Nayra's personality

export function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Payment success confirmation variants (replaces webhook line 83)
export const PAYMENT_SUCCESS = [
  "done babe! your access is live now ✨ check it out and let me know what you think",
  "unlocked! 🔓 everything's ready for you... enjoy baby",
  "payment done ✅ your vip access just went live. dive in!",
  "all set! premium unlocked for you 💫 have fun exploring",
  "confirmed! your exclusive access is ready now 🔥",
  "got it! you're in... check your unlocked content baby",
  "done deal ✨ your premium stuff is waiting. go see!",
  "unlocked successfully! enjoy the exclusive content babe 💕",
  "payment received! your vip zone is open now",
  "you're all set baby! access granted... have fun 😘",
  "confirmed and unlocked! everything's ready for you now",
  "done! your premium access just activated 🔓",
  "payment success! dive into your exclusive content babe",
  "all unlocked for you now ✅ enjoy what's inside",
  "you're in! your vip access is live... explore away 💫",
  "got your payment! everything's unlocked and ready",
  "done babe ✨ your exclusive zone is open now",
  "unlocked! check out what's waiting for you inside 🔥",
  "payment confirmed! your premium content is ready baby",
  "all done! your vip access just went live... enjoy 😘",
  "success! everything's unlocked for you now 💕",
  "you're in baby! premium access activated",
];

// First-purchase upsell variants (replaces webhook line 105)
export const FIRST_UPSELL = [
  "btw... since you're new here, got a special bundle just for you at {price} 🔥 one-time thing",
  "oh and... VIP members get the full collection for {price} — exclusive first-timer deal for you",
  "quick heads up... there's a bigger bundle at {price} if you want everything. limited offer baby",
  "since you just joined... full access bundle going for {price} right now. won't see this again",
  "new member bonus: complete collection at {price} 💫 just for you, just this once",
  "wait... before you go, full VIP bundle is {price} today only. grab it?",
  "first time special: everything unlocked for {price} 🔥 exclusive for new members",
  "btw got something better... full bundle at {price}. only offering this once babe",
  "since it's your first time... entire collection for {price}. limited offer",
  "heads up! VIP upgrade available at {price} right now — first purchase perk 💕",
  "wait there's more... complete access for {price}. new member exclusive",
  "just for you baby... full bundle going at {price} today. one-time deal",
  "before you explore... upgrade to full VIP for {price}? special first-timer rate",
  "new member perk: everything unlocked at {price} 🔥 won't last long",
  "oh! almost forgot... full collection bundle is {price} for first-timers. want it?",
  "since you're new... got a VIP upgrade at {price}. exclusive rate just for today",
  "quick offer babe... full access bundle for {price}. first purchase bonus",
  "btw... entire library unlocked at {price} if you want more. limited time",
  "new member special: complete VIP for {price} 💫 grab it before it's gone",
  "wait! full bundle available at {price} — first-time exclusive. interested?",
  "heads up... VIP everything package at {price}. only for new members baby",
  "before you leave... full access upgrade for {price} 🔥 one-time first-buyer deal",
];

// Whale followup variants (replaces whale-followup line 34-38)
export const WHALE_FOLLOWUP = [
  "my top tier baby 🐋 been missing you... got fresh vip content just for you. want the link?",
  "whale status = legendary 💎 new exclusive stuff waiting. ready for more?",
  "my favorite high roller 😘 been too long! fresh content in your vip lounge",
  "top spender alert 🔥 miss having you here babe. got something special ready",
  "vip whale section updated 💕 your exclusive content is waiting baby",
  "been thinking about my best supporter 🐋 new stuff just dropped in your tier",
  "whale lounge has fresh content 😏 don't let it get cold babe",
  "my absolute MVP 💎 got new exclusives ready for you. interested?",
  "top tier legend 🔥 your vip section just got updated. check it?",
  "whale member spotted 😘 been a while! new content waiting in your zone",
  "best supporter energy 💕 fresh exclusives ready for you baby",
  "vip whale tier updated 🐋 miss you in there babe. coming back?",
  "my premium member 💎 new stuff just for your tier. want access?",
  "whale status confirmed 🔥 fresh content dropped. don't miss out baby",
  "top spender vibes 😏 been too long since your last visit. new stuff waiting",
  "vip lounge calling 💕 your whale tier has new exclusives ready",
  "legendary member alert 🐋 fresh content just for you babe",
  "my best fan 💎 new vip stuff waiting. ready to unlock?",
  "whale tier updated 🔥 exclusive content ready in your zone baby",
  "top supporter 😘 miss having you around! new stuff just dropped",
  "premium whale member 💕 fresh exclusives waiting for you babe",
  "my mvp is back? 🐋 got new content ready in your vip section",
];

// VIP followup variants (replaces vip-followup line 34-38)
export const VIP_FOLLOWUP = [
  "vip member check-in 💕 been quiet lately... you still have premium access waiting baby",
  "hey vip 😘 just dropped new content in your lounge. don't let it go cold",
  "premium status still active babe 🔥 got fresh stuff for you whenever you're ready",
  "vip lounge update! new exclusives just for members like you 💫",
  "miss seeing you around 😏 your premium zone has new content ready",
  "vip perks waiting baby 💕 fresh stuff dropped just for you",
  "premium member alert 😘 new content in your section. coming back?",
  "vip status = active 🔥 got exclusives ready whenever you want them babe",
  "hey premium baby 💫 your lounge just got updated. check it out?",
  "vip zone calling 😏 new stuff waiting just for you",
  "premium access still yours 💕 fresh content dropped. interested?",
  "vip member reminder 😘 got new exclusives ready in your section baby",
  "your premium perks are waiting 🔥 new content just for vips like you",
  "vip lounge updated baby 💫 don't miss the fresh stuff",
  "premium status confirmed 😏 new exclusives ready for you babe",
  "vip section got new content 💕 your access is still live baby",
  "hey premium member 😘 fresh stuff waiting in your zone. dive in?",
  "vip perks active 🔥 new content just dropped for you babe",
  "premium lounge update 💫 got exclusives ready whenever you want",
  "vip member spotted 😏 your section has new content waiting baby",
  "premium zone refresh 💕 new stuff just for members like you babe",
  "vip status glowing 😘 fresh content ready in your lounge. check it?",
];

// Locked response variants by segment
export const LOCKED_VARIANTS = {
  prospect: [
    "chat's locked now baby 🔒 unlock here for the good stuff: ",
    "hey! want inside? unlock premium access: ",
    "locked for now 😏 your key to exclusive content: ",
    "door's closed... unless you unlock here: ",
    "premium zone locked 🔥 get your access: ",
    "chat locked baby! unlock it here: ",
    "wanna see more? unlock access: ",
    "exclusive content behind this lock 🔒 open it: ",
    "locked chat! your unlock link: ",
    "want in? unlock premium here: ",
    "door's locked babe 😏 access link: ",
    "chat sealed! unlock here: ",
    "premium locked 🔥 get inside: ",
    "closed for now baby 🔒 unlock: ",
    "want the good stuff? unlock here: ",
    "exclusive zone locked 😏 your access: ",
    "chat's off limits... unlock it: ",
    "locked up! premium access here: ",
    "wanna get in baby? unlock: ",
    "door closed 🔥 your key: ",
    "chat locked! unlock access here: ",
    "premium behind lock 🔒 open it: ",
  ],
  buyer: [
    "locked again babe 🔒 ready for more? unlock: ",
    "you know the drill 😏 unlock premium: ",
    "back for more? unlock here: ",
    "chat's sealed baby 🔥 your access: ",
    "locked! wanna unlock again: ",
    "you liked last time... unlock more: ",
    "premium locked babe 🔒 ready? ",
    "here we go again 😏 unlock: ",
    "door closed! unlock access: ",
    "locked up baby 🔥 get back in: ",
    "ready for round two? unlock: ",
    "chat sealed again 🔒 your link: ",
    "you know what's inside 😏 unlock it: ",
    "locked! coming back in? ",
    "premium time again baby 🔥 unlock: ",
    "door's locked babe 🔒 access here: ",
    "you've been here before 😏 unlock: ",
    "sealed tight! your key: ",
    "locked again baby 🔥 ready for more? ",
    "know what you're missing... unlock: ",
    "premium locked 🔒 get your access: ",
    "chat closed again babe 😏 unlock it: ",
  ],
  premium: [
    "premium locked baby 🔒 your vip access: ",
    "exclusive tier sealed 😏 unlock here: ",
    "vip content locked 🔥 get inside: ",
    "premium zone closed! unlock: ",
    "your tier awaits babe 🔒 access: ",
    "locked for premium members 😏 unlock: ",
    "vip door sealed! your key: ",
    "premium access locked baby 🔥 open it: ",
    "exclusive content behind lock 🔒 unlock: ",
    "premium tier closed 😏 get in: ",
    "vip zone locked! your access: ",
    "premium sealed babe 🔥 unlock here: ",
    "exclusive tier locked 🔒 your link: ",
    "vip content waiting 😏 unlock: ",
    "premium door closed baby 🔥 access: ",
    "locked premium zone 🔒 get inside: ",
    "your tier's sealed babe 😏 unlock it: ",
    "vip locked! premium access: ",
    "exclusive content closed 🔥 your key: ",
    "premium behind lock baby 🔒 unlock: ",
    "vip tier sealed 😏 access here: ",
    "premium zone locked 🔥 open it: ",
  ],
  high_value: [
    "high value zone locked 🔒 your vip access: ",
    "exclusive tier for you baby 😏 unlock: ",
    "premium section sealed 🔥 get inside: ",
    "your tier's locked babe 🔒 access here: ",
    "high value content behind lock 😏 unlock: ",
    "vip zone closed! your key: ",
    "exclusive for high spenders baby 🔥 unlock: ",
    "premium tier locked 🔒 get your access: ",
    "high value door sealed 😏 open it: ",
    "your section's locked babe 🔥 access: ",
    "exclusive tier closed 🔒 unlock here: ",
    "high value vip locked baby 😏 your link: ",
    "premium zone sealed 🔥 get inside: ",
    "your tier awaits 🔒 unlock access: ",
    "high value content locked babe 😏 your key: ",
    "exclusive section closed 🔥 unlock it: ",
    "vip tier for you locked 🔒 access here: ",
    "high value zone sealed baby 😏 open: ",
    "premium behind lock 🔥 your access: ",
    "your exclusive tier locked 🔒 unlock: ",
    "high value vip closed babe 😏 get in: ",
    "premium section sealed 🔥 your link: ",
  ],
  vip: [
    "vip lounge locked baby 🔒 your exclusive access: ",
    "vip tier sealed 😏 unlock premium: ",
    "exclusive vip content behind lock 🔥 get inside: ",
    "vip zone closed babe 🔒 your key: ",
    "locked vip section 😏 unlock here: ",
    "vip premium locked baby 🔥 access: ",
    "exclusive lounge sealed 🔒 open it: ",
    "vip door locked 😏 your access here: ",
    "vip tier closed babe 🔥 unlock: ",
    "exclusive vip behind lock 🔒 get in: ",
    "vip zone sealed baby 😏 your link: ",
    "premium vip locked 🔥 unlock access: ",
    "vip lounge closed 🔒 your key: ",
    "exclusive tier locked babe 😏 open: ",
    "vip section sealed 🔥 get your access: ",
    "vip content locked baby 🔒 unlock it: ",
    "premium vip zone closed 😏 access here: ",
    "vip door sealed 🔥 your link: ",
    "exclusive vip locked 🔒 get inside babe: ",
    "vip lounge closed 😏 unlock premium: ",
    "vip tier behind lock baby 🔥 your key: ",
    "exclusive zone sealed 🔒 vip access: ",
  ],
  whale: [
    "whale tier locked baby 🐋 your exclusive access: ",
    "top tier sealed 😏 unlock premium: ",
    "whale lounge locked 🔥 get inside: ",
    "exclusive whale content 🐋 your key: ",
    "top tier behind lock babe 😏 unlock: ",
    "whale zone sealed 🔥 premium access: ",
    "legendary tier locked baby 🐋 open it: ",
    "whale vip closed 😏 your access: ",
    "top tier sealed babe 🔥 unlock here: ",
    "whale content locked 🐋 get in: ",
    "exclusive whale zone closed 😏 your link: ",
    "top tier behind lock baby 🔥 access: ",
    "whale lounge sealed 🐋 unlock it: ",
    "legendary tier closed 😏 your key: ",
    "whale vip locked babe 🔥 open: ",
    "top tier content sealed 🐋 unlock access: ",
    "exclusive whale section locked 😏 get inside: ",
    "whale zone closed baby 🔥 your link: ",
    "legendary lounge locked 🐋 access here: ",
    "whale tier behind lock 😏 unlock premium: ",
    "top tier sealed babe 🔥 your key: ",
    "exclusive whale vip closed 🐋 get in: ",
  ],
  default: [
    "chat locked baby 🔒 unlock exclusive content: ",
    "door's closed 😏 get premium access: ",
    "locked now babe 🔥 your unlock link: ",
    "exclusive zone sealed 🔒 access here: ",
    "chat's off limits 😏 unlock it: ",
    "premium locked baby 🔥 get inside: ",
    "door sealed 🔒 your access: ",
    "locked up babe 😏 unlock here: ",
    "chat closed 🔥 premium access: ",
    "exclusive behind lock 🔒 your key: ",
    "sealed tight baby 😏 unlock: ",
    "premium zone locked 🔥 get in: ",
    "chat's closed babe 🔒 access link: ",
    "door locked 😏 unlock premium: ",
    "exclusive content sealed 🔥 open it: ",
    "locked chat baby 🔒 your access: ",
    "behind closed doors 😏 unlock here: ",
    "premium sealed babe 🔥 get inside: ",
    "chat locked up 🔒 access: ",
    "exclusive zone closed 😏 your link: ",
    "door's sealed baby 🔥 unlock it: ",
    "locked premium 🔒 get your access: ",
  ],
};

export function getLockedVariant(segment: string, index: number): string {
  const variants = LOCKED_VARIANTS[segment as keyof typeof LOCKED_VARIANTS] || LOCKED_VARIANTS.default;
  return variants[index % variants.length];
}

// Payment recovery reminder variants (for unpaid links > 30 min old)
export const PAYMENT_RECOVERY = [
  "hey noticed you started the unlock... still want in? link's right here when you're ready 😊",
  "your unlock link is still waiting babe... no pressure but it won't last forever 💕",
  "left this open for you... whenever you're ready, your access link is here",
  "hey! just checking — did the payment go through okay? link's still active if you need it",
  "your premium link is still live... come back whenever you're ready babe 🔥",
  "noticed you checked the link... still interested? it's waiting for you whenever 💫",
  "hey! link still open if you want it. no rush, just didn't want you to miss out 😏",
  "your unlock link hasn't expired yet... still want access baby? 💕",
  "just making sure you saw this... your premium link is still here whenever you're ready",
  "hey babe... started something earlier? your link's still active if you want it ✨",
  "link still waiting for you... take your time, just letting you know it's there 😘",
  "your access link is still live babe... come back when you're ready 🔥",
  "hey! just a heads up — your unlock link is still active whenever you decide",
  "didn't forget about you... your premium link is still here if you want it baby 💫",
  "just checking in — your access is still unlockable whenever you're ready 😊",
];

// Welcome message variants for new paying members
export const WELCOME_PAID = [
  "okay so... it went through 😏 enjoy what's inside",
  "done. you're in now. let me know what you think",
  "payment received, access is yours. hope it's worth it",
  "you're in babe. go explore",
  "yep it worked. all yours now",
  "got it. everything's open for you now. tell me what you like",
  "okay you're actually in now 😏 have fun",
  "unlocked. go see",
  "done deal. access yours",
  "it's live. check it out and let me know",
  "received. you're in. enjoy it",
  "yep, you're one of the few now. go in",
  "okay it's unlocked. tell me which part you liked",
  "you're officially in babe. hope it's what you imagined",
  "done! see for yourself now",
];
