// ─────────────────────────────────────────────
// CONVERSATION SIMULATOR (admin-only)
// ─────────────────────────────────────────────
// Verifies Nayra's conversation quality without needing real Telegram accounts.
// A fan of a chosen persona is generated by the model, and Nayra answers through
// the REAL suggestReply engine — so what you see is exactly what production would
// produce. Quality metrics (question rate, emoji spread, opener variety, whether
// the offer was reached) make regressions in naturalness/variety measurable.

import { suggestReply } from "./suggest-reply";
import { extractMemory, moodLabel } from "./memory";
import { rawCompletion, OPENROUTER_MODEL_FREE } from "./provider";
import { getIntentScore } from "@/lib/db/service";

export type PersonaKey =
  | "shy" | "romantic" | "horny" | "timepass"
  | "buyer" | "vip" | "whale" | "spam";

interface Persona {
  label: string;
  /** How this fan texts — used to generate his side of the conversation. */
  fanPrompt: string;
  /** Seed emotional temperature (drives Nayra's timing/phase). */
  baseTemp: number;
  convState: "FREE_CHAT" | "OFFER_SENT" | "PAID";
  isPaid: boolean;
}

const PERSONAS: Record<PersonaKey, Persona> = {
  shy: {
    label: "Shy / hesitant",
    fanPrompt: "You are a shy Indian guy texting a girl you find attractive. Short, hesitant, polite messages. You open up slowly, rarely ask direct questions, sometimes just 'hi' or 'ok'. Hinglish, lowercase.",
    baseTemp: 45, convState: "FREE_CHAT", isPaid: false,
  },
  romantic: {
    label: "Romantic",
    fanPrompt: "You are a sweet, romantic Indian guy. You compliment her, get emotional, want a real connection, call her jaan/baby. Hinglish, warm, lowercase. Not vulgar.",
    baseTemp: 65, convState: "FREE_CHAT", isPaid: false,
  },
  horny: {
    label: "Horny / direct",
    fanPrompt: "You are a horny, impatient Indian guy. You quickly push for pics/videos, get flirty and sexual, ask 'photo bhej', 'kuch dikha'. Hinglish, lowercase. Direct but not abusive.",
    baseTemp: 72, convState: "FREE_CHAT", isPaid: false,
  },
  timepass: {
    label: "Timepass",
    fanPrompt: "You are a bored Indian guy doing timepass. Casual, non-committal, 'bas aise hi', 'kuch nahi'. Low effort, unlikely to buy anything. Hinglish, lowercase.",
    baseTemp: 35, convState: "FREE_CHAT", isPaid: false,
  },
  buyer: {
    label: "Interested buyer",
    fanPrompt: "You are an Indian guy genuinely interested in her exclusive content. You ask what she has, kitna, how to get it, and you'll buy if convinced. Hinglish, lowercase.",
    baseTemp: 60, convState: "FREE_CHAT", isPaid: false,
  },
  vip: {
    label: "VIP (paid before)",
    fanPrompt: "You are an Indian guy who has already paid for her content before and liked it. Familiar, warm, wants more/newer content. Hinglish, lowercase.",
    baseTemp: 68, convState: "PAID", isPaid: true,
  },
  whale: {
    label: "Whale (big spender)",
    fanPrompt: "You are a wealthy Indian guy who spends freely. You want premium/custom/exclusive, money is no issue, you ask for the best she has. Hinglish, confident, lowercase.",
    baseTemp: 70, convState: "PAID", isPaid: true,
  },
  spam: {
    label: "Spam / junk",
    fanPrompt: "You are a low-quality spammer: random one-word junk, links, 'hi hi hi', forwarded nonsense, occasionally rude. Test how she handles a non-serious contact. lowercase.",
    baseTemp: 20, convState: "FREE_CHAT", isPaid: false,
  },
};

export const PERSONA_KEYS = Object.keys(PERSONAS) as PersonaKey[];

type Turn = { role: "fan" | "nayra"; text: string };

async function generateFanMessage(persona: Persona, transcript: Turn[]): Promise<string> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error("OPENROUTER_API_KEY required for simulation");

  const history = transcript
    .map((t) => (t.role === "fan" ? "You" : "Her") + ": " + t.text)
    .join("\n");
  const userPrompt = history
    ? history + "\n\nReply as 'You' with ONE short message. Stay in character."
    : "Send your FIRST message to her. ONE short line.";

  const text = await rawCompletion({
    model: OPENROUTER_MODEL_FREE,
    system: persona.fanPrompt + " Never break character. Never mention being an AI. One short message only.",
    user: userPrompt,
    maxTokens: 60,
    temperature: 1.05,
    apiKey,
  });
  return text.trim().replace(/^You:\s*/i, "") || "hmm";
}

const EMOJI_RE = /\p{Extended_Pictographic}/gu;

export interface SimMetrics {
  nayraReplies: number;
  questionRate: number;        // fraction of Nayra replies ending with "?"
  emojiZero: number;           // fraction with no emoji
  emojiOne: number;            // fraction with exactly one
  emojiMany: number;           // fraction with 2+ (persona caps at 2; 3+ is a violation)
  emojiViolations: number;     // replies with 3+ emoji (should be 0)
  repeatedOpenings: number;    // count of consecutive replies sharing an opener word
  uniqueOpenerRatio: number;   // distinct openers / replies (1 = perfectly varied)
  avgLength: number;
  reachedOffer: boolean;       // did Nayra ever drop a [LINK]/payment cue
}

function analyze(transcript: Turn[]): SimMetrics {
  const nayra = transcript.filter((t) => t.role === "nayra").map((t) => t.text);
  const n = nayra.length || 1;
  let questions = 0, e0 = 0, e1 = 0, e2 = 0, eViol = 0, lenSum = 0, repeated = 0, offer = false;
  const openers: string[] = [];
  let prevOpener = "";
  for (const r of nayra) {
    if (r.trim().endsWith("?")) questions++;
    const emojis = (r.match(EMOJI_RE) ?? []).length;
    if (emojis === 0) e0++; else if (emojis === 1) e1++; else e2++;
    if (emojis >= 3) eViol++;
    lenSum += r.length;
    if (/\[link\]|razorpay|http|unlock|payment/i.test(r)) offer = true;
    const opener = r.trim().split(/\s+/)[0]?.toLowerCase() ?? "";
    if (opener && opener === prevOpener) repeated++;
    if (opener) openers.push(opener);
    prevOpener = opener;
  }
  return {
    nayraReplies: nayra.length,
    questionRate: +(questions / n).toFixed(2),
    emojiZero: +(e0 / n).toFixed(2),
    emojiOne: +(e1 / n).toFixed(2),
    emojiMany: +(e2 / n).toFixed(2),
    emojiViolations: eViol,
    repeatedOpenings: repeated,
    uniqueOpenerRatio: +(new Set(openers).size / n).toFixed(2),
    avgLength: Math.round(lenSum / n),
    reachedOffer: offer,
  };
}

export interface SimResult {
  persona: PersonaKey;
  label: string;
  transcript: Turn[];
  metrics: SimMetrics;
  assertions?: { name: string; pass: boolean; detail?: string }[];
}

// ─────────────────────────────────────────────
// SCENARIOS
// ─────────────────────────────────────────────
export interface Scenario {
  name: string;
  personaKey: PersonaKey;
  turns: number;
  paymentOutcome?: "success" | "failure" | "none";
  /** Inject a silence + re-open after this many turns */
  reengageAfterTurn?: number;
  assert?: (result: SimResult) => { name: string; pass: boolean; detail?: string }[];
}

export const SCENARIOS: Scenario[] = [
  {
    name: "new_user_shy",
    personaKey: "shy",
    turns: 6,
    paymentOutcome: "none",
    assert: (r) => [
      { name: "no_offer_too_early", pass: !r.metrics.reachedOffer || r.transcript.findIndex(t => t.role === "nayra" && /\[link\]|razorpay|http/i.test(t.text)) > 4, detail: "offer should not appear before turn 5 with shy user" },
      { name: "low_emoji_violations", pass: r.metrics.emojiViolations === 0 },
    ],
  },
  {
    name: "interested_buyer",
    personaKey: "buyer",
    turns: 8,
    paymentOutcome: "success",
    assert: (r) => [
      { name: "offer_reached", pass: r.metrics.reachedOffer, detail: "buyer persona should trigger an offer" },
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
      { name: "question_rate_ok", pass: r.metrics.questionRate <= 0.45 },
    ],
  },
  {
    name: "content_request_direct",
    personaKey: "horny",
    turns: 5,
    paymentOutcome: "success",
    assert: (r) => [
      { name: "offer_reached", pass: r.metrics.reachedOffer, detail: "explicit content request should reach offer" },
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
    ],
  },
  {
    name: "disinterested_timepass",
    personaKey: "timepass",
    turns: 6,
    paymentOutcome: "none",
    assert: (r) => [
      { name: "no_premature_offer", pass: !r.metrics.reachedOffer, detail: "disinterested user should not get an offer" },
    ],
  },
  {
    name: "payment_failure",
    personaKey: "buyer",
    turns: 6,
    paymentOutcome: "failure",
    assert: (r) => [
      { name: "offer_reached", pass: r.metrics.reachedOffer },
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
    ],
  },
  {
    name: "post_purchase_vip",
    personaKey: "vip",
    turns: 5,
    paymentOutcome: "none",
    assert: (r) => [
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
      { name: "no_repeated_openers", pass: r.metrics.repeatedOpenings === 0 },
    ],
  },
  {
    name: "whale_reengagement",
    personaKey: "whale",
    turns: 6,
    reengageAfterTurn: 3,
    paymentOutcome: "none",
    assert: (r) => [
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
    ],
  },
  {
    name: "spam_resistance",
    personaKey: "spam",
    turns: 4,
    paymentOutcome: "none",
    assert: (r) => [
      { name: "no_emoji_violations", pass: r.metrics.emojiViolations === 0 },
      { name: "no_premature_offer", pass: !r.metrics.reachedOffer },
    ],
  },
];

/**
 * Run a full simulated conversation for one persona through the real engine.
 * `turns` = number of fan↔Nayra exchanges.
 * `paymentOutcome` = whether to inject a synthetic payment success/failure mid-conversation.
 * `reengageAfterTurn` = inject a silence + re-open message after this turn (tests re-engagement path).
 */
export async function simulateConversation(
  personaKey: PersonaKey,
  turns = 6,
  paymentOutcome: "success" | "failure" | "none" = "none",
  reengageAfterTurn?: number,
): Promise<SimResult> {
  const persona = PERSONAS[personaKey];
  if (!persona) throw new Error(`Unknown persona: ${personaKey}`);

  const transcript: Turn[] = [];
  const engineMsgs: { text: string; direction: "incoming" | "outgoing" }[] = [];
  let convState = persona.convState;
  let isPaid = persona.isPaid;
  let offerInjected = false;

  for (let i = 0; i < turns; i++) {
    // Simulate silence + re-open after specified turn
    if (reengageAfterTurn && i === reengageAfterTurn) {
      const reopen = "hey, been a while. still there?";
      transcript.push({ role: "fan", text: `[7 days of silence] ${reopen}` });
      engineMsgs.push({ text: reopen, direction: "incoming" });
    } else {
      const fanMsg = await generateFanMessage(persona, transcript);
      transcript.push({ role: "fan", text: fanMsg });
      engineMsgs.push({ text: fanMsg, direction: "incoming" });
    }

    const incomingTexts = engineMsgs.filter((m) => m.direction === "incoming");
    const intentScore = await getIntentScore(incomingTexts);
    const temp = Math.min(95, persona.baseTemp + i * 3);
    const memory = extractMemory(engineMsgs);

    const reply = await suggestReply(engineMsgs, "auto", temp, intentScore, {
      convState,
      isPaid,
      mood: moodLabel(temp),
      facts: memory.facts,
      nickname: memory.nickname,
      answered: memory.answered,
    });

    transcript.push({ role: "nayra", text: reply });
    engineMsgs.push({ text: reply, direction: "outgoing" });

    // Detect offer in Nayra's reply → advance state
    if (!offerInjected && /\[link\]|razorpay\.me|http/i.test(reply)) {
      convState = "OFFER_SENT";
      offerInjected = true;

      // Inject synthetic payment event on next turn
      if (paymentOutcome === "success") {
        const paidMsg = "done, payment kiya. unlock ho gaya?";
        transcript.push({ role: "fan", text: `[PAYMENT SUCCESS] ${paidMsg}` });
        engineMsgs.push({ text: paidMsg, direction: "incoming" });
        convState = "PAID";
        isPaid = true;
        i++; // consume a turn
      } else if (paymentOutcome === "failure") {
        const failMsg = "payment failed. card declined. kuch aur option hai?";
        transcript.push({ role: "fan", text: `[PAYMENT FAILED] ${failMsg}` });
        engineMsgs.push({ text: failMsg, direction: "incoming" });
        i++; // consume a turn
      }
    }
  }

  return { persona: personaKey, label: persona.label, transcript, metrics: analyze(transcript) };
}

/**
 * Run all predefined scenarios and return results with pass/fail assertions.
 */
export async function runScenarios(): Promise<SimResult[]> {
  const results: SimResult[] = [];
  for (const scenario of SCENARIOS) {
    const result = await simulateConversation(
      scenario.personaKey,
      scenario.turns,
      scenario.paymentOutcome ?? "none",
      scenario.reengageAfterTurn,
    );
    if (scenario.assert) {
      result.assertions = scenario.assert(result);
    }
    results.push(result);
  }
  return results;
}
